import { forwardRef } from "react";
import type { Icon } from "@phosphor-icons/react";
import type { LucideProps } from "lucide-react";
export type { LucideIcon, LucideProps } from "lucide-react";
import { ArrowCounterClockwise as PhArrowCounterClockwise } from "@phosphor-icons/react/dist/ssr/ArrowCounterClockwise";
import { ArrowDownRight as PhArrowDownRight } from "@phosphor-icons/react/dist/ssr/ArrowDownRight";
import { ArrowLeft as PhArrowLeft } from "@phosphor-icons/react/dist/ssr/ArrowLeft";
import { ArrowRight as PhArrowRight } from "@phosphor-icons/react/dist/ssr/ArrowRight";
import { ArrowUpRight as PhArrowUpRight } from "@phosphor-icons/react/dist/ssr/ArrowUpRight";
import { ArrowsClockwise as PhArrowsClockwise } from "@phosphor-icons/react/dist/ssr/ArrowsClockwise";
import { ArrowsIn as PhArrowsIn } from "@phosphor-icons/react/dist/ssr/ArrowsIn";
import { ArrowsLeftRight as PhArrowsLeftRight } from "@phosphor-icons/react/dist/ssr/ArrowsLeftRight";
import { ArrowsOut as PhArrowsOut } from "@phosphor-icons/react/dist/ssr/ArrowsOut";
import { ArrowsOutCardinal as PhArrowsOutCardinal } from "@phosphor-icons/react/dist/ssr/ArrowsOutCardinal";
import { Bank as PhBank } from "@phosphor-icons/react/dist/ssr/Bank";
import { Bell as PhBell } from "@phosphor-icons/react/dist/ssr/Bell";
import { BookBookmark as PhBookBookmark } from "@phosphor-icons/react/dist/ssr/BookBookmark";
import { BookOpen as PhBookOpen } from "@phosphor-icons/react/dist/ssr/BookOpen";
import { Briefcase as PhBriefcase } from "@phosphor-icons/react/dist/ssr/Briefcase";
import { Broadcast as PhBroadcast } from "@phosphor-icons/react/dist/ssr/Broadcast";
import { Buildings as PhBuildings } from "@phosphor-icons/react/dist/ssr/Buildings";
import { Calculator as PhCalculator } from "@phosphor-icons/react/dist/ssr/Calculator";
import { Calendar as PhCalendar } from "@phosphor-icons/react/dist/ssr/Calendar";
import { CalendarCheck as PhCalendarCheck } from "@phosphor-icons/react/dist/ssr/CalendarCheck";
import { CalendarDots as PhCalendarDots } from "@phosphor-icons/react/dist/ssr/CalendarDots";
import { CaretDown as PhCaretDown } from "@phosphor-icons/react/dist/ssr/CaretDown";
import { CaretLeft as PhCaretLeft } from "@phosphor-icons/react/dist/ssr/CaretLeft";
import { CaretRight as PhCaretRight } from "@phosphor-icons/react/dist/ssr/CaretRight";
import { CaretUp as PhCaretUp } from "@phosphor-icons/react/dist/ssr/CaretUp";
import { ChartBar as PhChartBar } from "@phosphor-icons/react/dist/ssr/ChartBar";
import { ChartLineUp as PhChartLineUp } from "@phosphor-icons/react/dist/ssr/ChartLineUp";
import { ChatCircle as PhChatCircle } from "@phosphor-icons/react/dist/ssr/ChatCircle";
import { ChatText as PhChatText } from "@phosphor-icons/react/dist/ssr/ChatText";
import { Check as PhCheck } from "@phosphor-icons/react/dist/ssr/Check";
import { CheckCircle as PhCheckCircle } from "@phosphor-icons/react/dist/ssr/CheckCircle";
import { CheckSquare as PhCheckSquare } from "@phosphor-icons/react/dist/ssr/CheckSquare";
import { Checks as PhChecks } from "@phosphor-icons/react/dist/ssr/Checks";
import { Circle as PhCircle } from "@phosphor-icons/react/dist/ssr/Circle";
import { ClipboardText as PhClipboardText } from "@phosphor-icons/react/dist/ssr/ClipboardText";
import { Clock as PhClock } from "@phosphor-icons/react/dist/ssr/Clock";
import { ClockCounterClockwise as PhClockCounterClockwise } from "@phosphor-icons/react/dist/ssr/ClockCounterClockwise";
import { CurrencyDollar as PhCurrencyDollar } from "@phosphor-icons/react/dist/ssr/CurrencyDollar";
import { DotsSixVertical as PhDotsSixVertical } from "@phosphor-icons/react/dist/ssr/DotsSixVertical";
import { DotsThree as PhDotsThree } from "@phosphor-icons/react/dist/ssr/DotsThree";
import { DownloadSimple as PhDownloadSimple } from "@phosphor-icons/react/dist/ssr/DownloadSimple";
import { EnvelopeSimple as PhEnvelopeSimple } from "@phosphor-icons/react/dist/ssr/EnvelopeSimple";
import { Eye as PhEye } from "@phosphor-icons/react/dist/ssr/Eye";
import { EyeSlash as PhEyeSlash } from "@phosphor-icons/react/dist/ssr/EyeSlash";
import { FileText as PhFileText } from "@phosphor-icons/react/dist/ssr/FileText";
import { FileXls as PhFileXls } from "@phosphor-icons/react/dist/ssr/FileXls";
import { Flag as PhFlag } from "@phosphor-icons/react/dist/ssr/Flag";
import { Flame as PhFlame } from "@phosphor-icons/react/dist/ssr/Flame";
import { FloppyDisk as PhFloppyDisk } from "@phosphor-icons/react/dist/ssr/FloppyDisk";
import { FolderPlus as PhFolderPlus } from "@phosphor-icons/react/dist/ssr/FolderPlus";
import { Funnel as PhFunnel } from "@phosphor-icons/react/dist/ssr/Funnel";
import { GearSix as PhGearSix } from "@phosphor-icons/react/dist/ssr/GearSix";
import { GitBranch as PhGitBranch } from "@phosphor-icons/react/dist/ssr/GitBranch";
import { GlobeHemisphereWest as PhGlobeHemisphereWest } from "@phosphor-icons/react/dist/ssr/GlobeHemisphereWest";
import { GraduationCap as PhGraduationCap } from "@phosphor-icons/react/dist/ssr/GraduationCap";
import { IdentificationCard as PhIdentificationCard } from "@phosphor-icons/react/dist/ssr/IdentificationCard";
import { InstagramLogo as PhInstagramLogo } from "@phosphor-icons/react/dist/ssr/InstagramLogo";
import { Kanban as PhKanban } from "@phosphor-icons/react/dist/ssr/Kanban";
import { Keyboard as PhKeyboard } from "@phosphor-icons/react/dist/ssr/Keyboard";
import { Lifebuoy as PhLifebuoy } from "@phosphor-icons/react/dist/ssr/Lifebuoy";
import { Lightbulb as PhLightbulb } from "@phosphor-icons/react/dist/ssr/Lightbulb";
import { Lightning as PhLightning } from "@phosphor-icons/react/dist/ssr/Lightning";
import { LinkedinLogo as PhLinkedinLogo } from "@phosphor-icons/react/dist/ssr/LinkedinLogo";
import { List as PhList } from "@phosphor-icons/react/dist/ssr/List";
import { ListChecks as PhListChecks } from "@phosphor-icons/react/dist/ssr/ListChecks";
import { Lock as PhLock } from "@phosphor-icons/react/dist/ssr/Lock";
import { MagicWand as PhMagicWand } from "@phosphor-icons/react/dist/ssr/MagicWand";
import { MagnifyingGlass as PhMagnifyingGlass } from "@phosphor-icons/react/dist/ssr/MagnifyingGlass";
import { MapPin as PhMapPin } from "@phosphor-icons/react/dist/ssr/MapPin";
import { Medal as PhMedal } from "@phosphor-icons/react/dist/ssr/Medal";
import { MegaphoneSimple as PhMegaphoneSimple } from "@phosphor-icons/react/dist/ssr/MegaphoneSimple";
import { MinusCircle as PhMinusCircle } from "@phosphor-icons/react/dist/ssr/MinusCircle";
import { Moon as PhMoon } from "@phosphor-icons/react/dist/ssr/Moon";
import { PaperPlaneTilt as PhPaperPlaneTilt } from "@phosphor-icons/react/dist/ssr/PaperPlaneTilt";
import { Paperclip as PhPaperclip } from "@phosphor-icons/react/dist/ssr/Paperclip";
import { PauseCircle as PhPauseCircle } from "@phosphor-icons/react/dist/ssr/PauseCircle";
import { PencilSimple as PhPencilSimple } from "@phosphor-icons/react/dist/ssr/PencilSimple";
import { Phone as PhPhone } from "@phosphor-icons/react/dist/ssr/Phone";
import { Play as PhPlay } from "@phosphor-icons/react/dist/ssr/Play";
import { PlusCircle as PhPlusCircle } from "@phosphor-icons/react/dist/ssr/PlusCircle";
import { Power as PhPower } from "@phosphor-icons/react/dist/ssr/Power";
import { Prohibit as PhProhibit } from "@phosphor-icons/react/dist/ssr/Prohibit";
import { Pulse as PhPulse } from "@phosphor-icons/react/dist/ssr/Pulse";
import { RadioButton as PhRadioButton } from "@phosphor-icons/react/dist/ssr/RadioButton";
import { Receipt as PhReceipt } from "@phosphor-icons/react/dist/ssr/Receipt";
import { Repeat as PhRepeat } from "@phosphor-icons/react/dist/ssr/Repeat";
import { Rows as PhRows } from "@phosphor-icons/react/dist/ssr/Rows";
import { Shield as PhShield } from "@phosphor-icons/react/dist/ssr/Shield";
import { ShieldCheck as PhShieldCheck } from "@phosphor-icons/react/dist/ssr/ShieldCheck";
import { ShieldWarning as PhShieldWarning } from "@phosphor-icons/react/dist/ssr/ShieldWarning";
import { ShoppingBag as PhShoppingBag } from "@phosphor-icons/react/dist/ssr/ShoppingBag";
import { Sidebar as PhSidebar } from "@phosphor-icons/react/dist/ssr/Sidebar";
import { SignOut as PhSignOut } from "@phosphor-icons/react/dist/ssr/SignOut";
import { SlidersHorizontal as PhSlidersHorizontal } from "@phosphor-icons/react/dist/ssr/SlidersHorizontal";
import { Snowflake as PhSnowflake } from "@phosphor-icons/react/dist/ssr/Snowflake";
import { Sparkle as PhSparkle } from "@phosphor-icons/react/dist/ssr/Sparkle";
import { SpinnerGap as PhSpinnerGap } from "@phosphor-icons/react/dist/ssr/SpinnerGap";
import { Square as PhSquare } from "@phosphor-icons/react/dist/ssr/Square";
import { SquaresFour as PhSquaresFour } from "@phosphor-icons/react/dist/ssr/SquaresFour";
import { Stack as PhStack } from "@phosphor-icons/react/dist/ssr/Stack";
import { Star as PhStar } from "@phosphor-icons/react/dist/ssr/Star";
import { Stethoscope as PhStethoscope } from "@phosphor-icons/react/dist/ssr/Stethoscope";
import { Sun as PhSun } from "@phosphor-icons/react/dist/ssr/Sun";
import { Tag as PhTag } from "@phosphor-icons/react/dist/ssr/Tag";
import { Target as PhTarget } from "@phosphor-icons/react/dist/ssr/Target";
import { Trash as PhTrash } from "@phosphor-icons/react/dist/ssr/Trash";
import { Tray as PhTray } from "@phosphor-icons/react/dist/ssr/Tray";
import { TrendDown as PhTrendDown } from "@phosphor-icons/react/dist/ssr/TrendDown";
import { TrendUp as PhTrendUp } from "@phosphor-icons/react/dist/ssr/TrendUp";
import { Trophy as PhTrophy } from "@phosphor-icons/react/dist/ssr/Trophy";
import { UploadSimple as PhUploadSimple } from "@phosphor-icons/react/dist/ssr/UploadSimple";
import { User as PhUser } from "@phosphor-icons/react/dist/ssr/User";
import { UserCheck as PhUserCheck } from "@phosphor-icons/react/dist/ssr/UserCheck";
import { UserCircle as PhUserCircle } from "@phosphor-icons/react/dist/ssr/UserCircle";
import { UserGear as PhUserGear } from "@phosphor-icons/react/dist/ssr/UserGear";
import { UserPlus as PhUserPlus } from "@phosphor-icons/react/dist/ssr/UserPlus";
import { Users as PhUsers } from "@phosphor-icons/react/dist/ssr/Users";
import { Wallet as PhWallet } from "@phosphor-icons/react/dist/ssr/Wallet";
import { Warning as PhWarning } from "@phosphor-icons/react/dist/ssr/Warning";
import { WarningCircle as PhWarningCircle } from "@phosphor-icons/react/dist/ssr/WarningCircle";
import { X as PhX } from "@phosphor-icons/react/dist/ssr/X";
import { XCircle as PhXCircle } from "@phosphor-icons/react/dist/ssr/XCircle";

// Solid silhouettes for objects, bold geometric strokes for directional controls.
function filledIcon(Component: Icon, name: string, weight: "fill" | "bold" = "fill") {
  const Result = forwardRef<SVGSVGElement, LucideProps>(function FilledIcon(
    { size = 24, strokeWidth: _stroke, absoluteStrokeWidth: _absolute, className, ...props }, ref,
  ) {
    return <Component {...props} ref={ref} size={size} weight={weight} className={["align-icon", className].filter(Boolean).join(" ")} aria-hidden={props["aria-label"] ? undefined : true} />;
  });
  Result.displayName = name;
  return Result;
}
export const Activity = filledIcon(PhPulse, "Activity", "bold");
export const AlertCircle = filledIcon(PhWarningCircle, "AlertCircle");
export const AlertTriangle = filledIcon(PhWarning, "AlertTriangle");
export const ArrowDownRight = filledIcon(PhArrowDownRight, "ArrowDownRight", "bold");
export const ArrowLeft = filledIcon(PhArrowLeft, "ArrowLeft", "bold");
export const ArrowRight = filledIcon(PhArrowRight, "ArrowRight", "bold");
export const ArrowRightLeft = filledIcon(PhArrowsLeftRight, "ArrowRightLeft", "bold");
export const ArrowUpRight = filledIcon(PhArrowUpRight, "ArrowUpRight", "bold");
export const Award = filledIcon(PhMedal, "Award");
export const Ban = filledIcon(PhProhibit, "Ban");
export const BarChart3 = filledIcon(PhChartBar, "BarChart3");
export const Bell = filledIcon(PhBell, "Bell");
export const Bolt = filledIcon(PhLightning, "Bolt");
export const BookCheck = filledIcon(PhBookBookmark, "BookCheck");
export const BookMarked = filledIcon(PhBookBookmark, "BookMarked");
export const BookOpen = filledIcon(PhBookOpen, "BookOpen");
export const Briefcase = filledIcon(PhBriefcase, "Briefcase");
export const Building = filledIcon(PhBuildings, "Building");
export const Building2 = filledIcon(PhBuildings, "Building2");
export const Calculator = filledIcon(PhCalculator, "Calculator");
export const Calendar = filledIcon(PhCalendar, "Calendar");
export const CalendarCheck = filledIcon(PhCalendarCheck, "CalendarCheck");
export const CalendarCheck2 = filledIcon(PhCalendarCheck, "CalendarCheck2");
export const CalendarClock = filledIcon(PhCalendarDots, "CalendarClock");
export const CalendarDays = filledIcon(PhCalendarDots, "CalendarDays");
export const Check = filledIcon(PhCheck, "Check", "bold");
export const CheckCheck = filledIcon(PhChecks, "CheckCheck", "bold");
export const CheckCircle2 = filledIcon(PhCheckCircle, "CheckCircle2");
export const CheckSquare = filledIcon(PhCheckSquare, "CheckSquare");
export const ChevronDown = filledIcon(PhCaretDown, "ChevronDown", "bold");
export const ChevronDownIcon = filledIcon(PhCaretDown, "ChevronDownIcon", "bold");
export const ChevronLeft = filledIcon(PhCaretLeft, "ChevronLeft", "bold");
export const ChevronLeftIcon = filledIcon(PhCaretLeft, "ChevronLeftIcon", "bold");
export const ChevronRight = filledIcon(PhCaretRight, "ChevronRight", "bold");
export const ChevronRightIcon = filledIcon(PhCaretRight, "ChevronRightIcon", "bold");
export const ChevronUp = filledIcon(PhCaretUp, "ChevronUp", "bold");
export const Circle = filledIcon(PhCircle, "Circle", "bold");
export const CircleDot = filledIcon(PhRadioButton, "CircleDot");
export const ClipboardList = filledIcon(PhClipboardText, "ClipboardList");
export const Clock = filledIcon(PhClock, "Clock");
export const Clock3 = filledIcon(PhClock, "Clock3");
export const Cog = filledIcon(PhGearSix, "Cog");
export const DollarSign = filledIcon(PhCurrencyDollar, "DollarSign");
export const Download = filledIcon(PhDownloadSimple, "Download");
export const Edit3 = filledIcon(PhPencilSimple, "Edit3");
export const Eye = filledIcon(PhEye, "Eye");
export const EyeOff = filledIcon(PhEyeSlash, "EyeOff");
export const FileBarChart = filledIcon(PhChartBar, "FileBarChart");
export const FileSpreadsheet = filledIcon(PhFileXls, "FileSpreadsheet");
export const FileText = filledIcon(PhFileText, "FileText");
export const FileWarning = filledIcon(PhFileText, "FileWarning");
export const Filter = filledIcon(PhFunnel, "Filter");
export const Flag = filledIcon(PhFlag, "Flag");
export const Flame = filledIcon(PhFlame, "Flame");
export const FolderPlus = filledIcon(PhFolderPlus, "FolderPlus");
export const GitBranch = filledIcon(PhGitBranch, "GitBranch");
export const Globe = filledIcon(PhGlobeHemisphereWest, "Globe");
export const GraduationCap = filledIcon(PhGraduationCap, "GraduationCap");
export const GripVertical = filledIcon(PhDotsSixVertical, "GripVertical");
export const History = filledIcon(PhClockCounterClockwise, "History");
export const IdCard = filledIcon(PhIdentificationCard, "IdCard");
export const Inbox = filledIcon(PhTray, "Inbox");
export const Instagram = filledIcon(PhInstagramLogo, "Instagram");
export const Kanban = filledIcon(PhKanban, "Kanban");
export const Keyboard = filledIcon(PhKeyboard, "Keyboard");
export const Landmark = filledIcon(PhBank, "Landmark");
export const Layers = filledIcon(PhStack, "Layers");
export const LayoutDashboard = filledIcon(PhSquaresFour, "LayoutDashboard");
export const LayoutGrid = filledIcon(PhSquaresFour, "LayoutGrid");
export const LifeBuoy = filledIcon(PhLifebuoy, "LifeBuoy");
export const Lightbulb = filledIcon(PhLightbulb, "Lightbulb");
export const LineChart = filledIcon(PhChartLineUp, "LineChart", "bold");
export const Linkedin = filledIcon(PhLinkedinLogo, "Linkedin");
export const List = filledIcon(PhList, "List", "bold");
export const ListChecks = filledIcon(PhListChecks, "ListChecks", "bold");
export const ListTodo = filledIcon(PhListChecks, "ListTodo", "bold");
export const Loader2 = filledIcon(PhSpinnerGap, "Loader2", "bold");
export const Lock = filledIcon(PhLock, "Lock");
export const LogOut = filledIcon(PhSignOut, "LogOut");
export const Mail = filledIcon(PhEnvelopeSimple, "Mail");
export const MapPin = filledIcon(PhMapPin, "MapPin");
export const Maximize2 = filledIcon(PhArrowsOut, "Maximize2");
export const Megaphone = filledIcon(PhMegaphoneSimple, "Megaphone");
export const MessageCircle = filledIcon(PhChatCircle, "MessageCircle");
export const MessageSquare = filledIcon(PhChatText, "MessageSquare");
export const Minimize2 = filledIcon(PhArrowsIn, "Minimize2");
export const Minus = filledIcon(PhMinusCircle, "Minus");
export const Moon = filledIcon(PhMoon, "Moon");
export const MoreHorizontal = filledIcon(PhDotsThree, "MoreHorizontal");
export const Move = filledIcon(PhArrowsOutCardinal, "Move");
export const PanelLeft = filledIcon(PhSidebar, "PanelLeft");
export const PanelLeftClose = filledIcon(PhSidebar, "PanelLeftClose");
export const PanelLeftOpen = filledIcon(PhSidebar, "PanelLeftOpen");
export const Paperclip = filledIcon(PhPaperclip, "Paperclip");
export const PauseCircle = filledIcon(PhPauseCircle, "PauseCircle");
export const Pencil = filledIcon(PhPencilSimple, "Pencil");
export const Phone = filledIcon(PhPhone, "Phone");
export const Play = filledIcon(PhPlay, "Play");
export const Plus = filledIcon(PhPlusCircle, "Plus");
export const Power = filledIcon(PhPower, "Power");
export const Radio = filledIcon(PhBroadcast, "Radio");
export const Receipt = filledIcon(PhReceipt, "Receipt");
export const RefreshCw = filledIcon(PhArrowsClockwise, "RefreshCw", "bold");
export const Repeat = filledIcon(PhRepeat, "Repeat");
export const RotateCcw = filledIcon(PhArrowCounterClockwise, "RotateCcw", "bold");
export const Rows3 = filledIcon(PhRows, "Rows3");
export const Save = filledIcon(PhFloppyDisk, "Save");
export const Search = filledIcon(PhMagnifyingGlass, "Search");
export const SearchCheck = filledIcon(PhMagnifyingGlass, "SearchCheck");
export const Send = filledIcon(PhPaperPlaneTilt, "Send");
export const Settings = filledIcon(PhGearSix, "Settings");
export const Settings2 = filledIcon(PhSlidersHorizontal, "Settings2");
export const Shield = filledIcon(PhShield, "Shield");
export const ShieldCheck = filledIcon(PhShieldCheck, "ShieldCheck");
export const ShieldX = filledIcon(PhShieldWarning, "ShieldX");
export const ShoppingBag = filledIcon(PhShoppingBag, "ShoppingBag");
export const Snowflake = filledIcon(PhSnowflake, "Snowflake");
export const Sparkles = filledIcon(PhSparkle, "Sparkles");
export const Square = filledIcon(PhSquare, "Square", "bold");
export const Star = filledIcon(PhStar, "Star");
export const StarOff = filledIcon(PhStar, "StarOff");
export const Stethoscope = filledIcon(PhStethoscope, "Stethoscope");
export const Sun = filledIcon(PhSun, "Sun");
export const Tag = filledIcon(PhTag, "Tag");
export const Tags = filledIcon(PhTag, "Tags");
export const Target = filledIcon(PhTarget, "Target");
export const Trash2 = filledIcon(PhTrash, "Trash2");
export const TrendingDown = filledIcon(PhTrendDown, "TrendingDown", "bold");
export const TrendingUp = filledIcon(PhTrendUp, "TrendingUp", "bold");
export const Trophy = filledIcon(PhTrophy, "Trophy");
export const Upload = filledIcon(PhUploadSimple, "Upload");
export const User = filledIcon(PhUser, "User");
export const UserCheck = filledIcon(PhUserCheck, "UserCheck");
export const UserCircle = filledIcon(PhUserCircle, "UserCircle");
export const UserCog = filledIcon(PhUserGear, "UserCog");
export const UserPlus = filledIcon(PhUserPlus, "UserPlus");
export const UserRound = filledIcon(PhUser, "UserRound");
export const Users = filledIcon(PhUsers, "Users");
export const Wallet = filledIcon(PhWallet, "Wallet");
export const Wand2 = filledIcon(PhMagicWand, "Wand2");
export const X = filledIcon(PhX, "X", "bold");
export const XCircle = filledIcon(PhXCircle, "XCircle");
export const Zap = filledIcon(PhLightning, "Zap");
